#!/bin/bash
#
# Skript kontrollib, kas käsurealt saadud täisarv on paaris või paaritu.

if [ $# -ne 1 ]; then
    echo "Käivita see skript koos arvuga, mille paarsust soovid kontrollida. Näiteks: ./yl2"
    exit 1
fi

arv=$1

if [ $((arv % 2)) -eq 0 ]; then
    echo "Antud arv on paaris"
else
    echo "Antud arv on paaritu"
fi
